version: '3.1'

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789 
      MYSQL_DATABASE: school_management
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123456789
